version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    hostname: kafka
    links:
    - zookeeper
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CREATE_TOPICS="tweets:2:2,analyzed-tweets:2:2"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
